name: Deployment

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  deploy-API-documentation:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'status' &&  github.event.state == 'success')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6 # Not needed with a .ruby-version file
          bundler-cache: true
      - name: Deployment script
        run: ./deploy.sh

  notify-failure:
    runs-on: ubuntu-latest
    needs: [deploy-API-documentation]
    if: ${{ failure() }}
    steps:
      - name: Notify Slack
        uses: archive/github-actions-slack@v2.0.1
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: cucumberstudio
          slack-optional-icon_emoji: ":fire:"
          slack-text: |
            [CucumberStudio API documentation]
            :fire_engine: Deployment failed <https://github.com/SmartBear/cucumberstudio-api-documentation/commit/${{github.sha}}>

  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          username: CucumberStudio API Documentation
          custom_payload: |
            {
              text: ":fire: Deployment THIS IS A TEST OF SLACK NOTIFICATION",
              attachments: [{
                        "color": "warning",
                        "title": "GitHub commit: ${{github.sha}}",
                        "title_link": ${{github.repository}}/commit/${{github.sha}},
                        "text": ${{github.event.commits[0].message}},
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}