name: Replicated release build

on:
  workflow_dispatch:

jobs:

  prepare-replicated-release:
    env:
      RR_USERNAME: ${{ secrets.REPLICATED_REGISTRY_USERNAME }}
      RR_PASSWORD: ${{ secrets.REPLICATED_REGISTRY_PASSWORD }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get replicated tag
        id: get_replicated_tag
        run: echo ::set-output name=VERSION::$( echo ${GITHUB_REF/refs\/tags\//} | cut -d'-' -f1)
      - name: Push the Docker image
        run: docker push registry.replicated.com/hiptest/cucumber-studio-api-documentation:${{steps.get_replicated_tag.outputs.VERSION}}

  notify-failuree:
    runs-on: ubuntu-latest
    needs: [prepare-replicated-release]
    #if: ${{ failure() }}
    steps:
      - name: Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              username: 'TEST Replicated Build CucumberStudio API Documentation',
              icon_emoji: ':cucumberstudio:'
              channel: '#cbo_test_channel',
              text: ":red_circle: Replicated release build for API Documentation failed",
              attachments: [{
                        "color": "danger",
                        "title": 'GitHub action: Replicated release build',
                        "title_link": 'https://github.com/${{github.repository}}/actions/workflows/replicated-release-build.yml
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}